plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = '1.0'
group = 'com.example.phantombomb'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = "21.1.169"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}